.TH "schultz_dash" 3 "Version 0.1.0" "Schultz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schultz_dash \- A registered dash pattern, as the renderer reads it\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schultz_resource\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBlengths\fP [SCHULTZ_DASH_MAX]"
.br
.ti -1c
.RI "uint32_t \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A registered dash pattern, as the renderer reads it\&. 
.PP
Definition at line \fB88\fP of file \fBschultz_resource\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "float schultz_dash::lengths[SCHULTZ_DASH_MAX]"
On, off, on, off, and so on\&. 
.PP
Definition at line \fB89\fP of file \fBschultz_resource\&.h\fP\&.
.SS "uint32_t schultz_dash::count"
How many lengths are used\&. 
.PP
Definition at line \fB90\fP of file \fBschultz_resource\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Schultz from the source code\&.
