.TH "schultz_file_filter" 3 "Version 0.1.0" "Schultz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schultz_file_filter \- One entry in a file dialog's list of what it will show\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schultz_window\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBpattern\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
One entry in a file dialog's list of what it will show\&. 
.PP
Definition at line \fB612\fP of file \fBschultz_window\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "const char* schultz_file_filter::name"
What the entry says, such as 'Text files'\&. 
.PP
Definition at line \fB613\fP of file \fBschultz_window\&.h\fP\&.
.SS "const char* schultz_file_filter::pattern"
The extensions it covers, separated by semicolons and without dots, such as \fC'txt;md'\fP\&. A single asterisk means everything\&. 
.PP
Definition at line \fB618\fP of file \fBschultz_window\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Schultz from the source code\&.
