.TH "schultz_patch_entry" 3 "Version 0.1.0" "Schultz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schultz_patch_entry \- One property setting inside a patch\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schultz_style\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBproperty\fP"
.br
.ti -1c
.RI "\fBschultz_value\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
One property setting inside a patch\&. 
.PP
Definition at line \fB287\fP of file \fBschultz_style\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t schultz_patch_entry::property"
One of the SCHULTZ_PROP_* values\&. 
.PP
Definition at line \fB288\fP of file \fBschultz_style\&.h\fP\&.
.SS "\fBschultz_value\fP schultz_patch_entry::value"
What it is set to\&. 
.PP
Definition at line \fB289\fP of file \fBschultz_style\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Schultz from the source code\&.
