.TH "schultz_size" 3 "Version 0.1.0" "Schultz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schultz_size \- A two dimensional extent in pixels\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schultz_geom\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBwidth\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A two dimensional extent in pixels\&. 
.PP
Definition at line \fB62\fP of file \fBschultz_geom\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "float schultz_size::width"
Horizontal extent\&. 
.PP
Definition at line \fB63\fP of file \fBschultz_geom\&.h\fP\&.
.SS "float schultz_size::height"
Vertical extent\&. 
.PP
Definition at line \fB64\fP of file \fBschultz_geom\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Schultz from the source code\&.
