.TH "schultz_grid_track" 3 "Version 0.1.0" "Schultz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schultz_grid_track \- One row or column definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schultz_layout\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBkind\fP"
.br
.ti -1c
.RI "float \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
One row or column definition\&. 
.PP
Definition at line \fB125\fP of file \fBschultz_layout\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t schultz_grid_track::kind"
One of SCHULTZ_TRACK_*\&. 
.PP
Definition at line \fB126\fP of file \fBschultz_layout\&.h\fP\&.
.SS "float schultz_grid_track::value"
Size for FIXED, weight for WEIGHTED, unused else\&. 
.PP
Definition at line \fB127\fP of file \fBschultz_layout\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Schultz from the source code\&.
