.TH "schultz_gradient_stop" 3 "Version 0.1.0" "Schultz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schultz_gradient_stop \- What a gradient's colour is at one point along it\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schultz_resource\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBoffset\fP"
.br
.ti -1c
.RI "\fBschultz_color\fP \fBcolor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
What a gradient's colour is at one point along it\&. 
.PP
Definition at line \fB61\fP of file \fBschultz_resource\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "float schultz_gradient_stop::offset"
0 at the start, 1 at the end\&. 
.PP
Definition at line \fB62\fP of file \fBschultz_resource\&.h\fP\&.
.SS "\fBschultz_color\fP schultz_gradient_stop::color"
The colour there\&. 
.PP
Definition at line \fB63\fP of file \fBschultz_resource\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Schultz from the source code\&.
