.TH "schultz_point" 3 "Version 0.1.0" "Schultz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schultz_point \- A position in pixels\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schultz_geom\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A position in pixels\&. 
.PP
Definition at line \fB48\fP of file \fBschultz_geom\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "float schultz_point::x"
Horizontal position, increasing to the right\&. 
.PP
Definition at line \fB49\fP of file \fBschultz_geom\&.h\fP\&.
.SS "float schultz_point::y"
Vertical position, increasing downward\&. 
.PP
Definition at line \fB50\fP of file \fBschultz_geom\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Schultz from the source code\&.
