.TH "schultz_rect" 3 "Version 0.1.0" "Schultz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
schultz_rect \- An axis aligned rectangle in pixels\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schultz_geom\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBwidth\fP"
.br
.ti -1c
.RI "float \fBheight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An axis aligned rectangle in pixels\&. 
.PP
Definition at line \fB54\fP of file \fBschultz_geom\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "float schultz_rect::x"
Left edge\&. 
.PP
Definition at line \fB55\fP of file \fBschultz_geom\&.h\fP\&.
.SS "float schultz_rect::y"
Top edge\&. 
.PP
Definition at line \fB56\fP of file \fBschultz_geom\&.h\fP\&.
.SS "float schultz_rect::width"
Extent to the right of x\&. 
.PP
Definition at line \fB57\fP of file \fBschultz_geom\&.h\fP\&.
.SS "float schultz_rect::height"
Extent below y\&. 
.PP
Definition at line \fB58\fP of file \fBschultz_geom\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Schultz from the source code\&.
