#!/bin/sh
#
# SPDX-License-Identifier: GPL-3.0-only
# Copyright 2026 Austin Lehman
#
# embed_fonts.sh - turns the bundled font files into a C source file.
#
# Writes the bundled faces from assets/fonts into one translation unit as
# string literals, so a program that links Schultz has working text without
# finding a file at runtime. Everything else the toolkit needs is already
# compiled in; the fonts were the last thing that was not.
#
# Five DejaVu faces for text and one Noto face for emoji. The emoji face is
# here for the same reason as the others: a font found on the system is a
# different picture on every platform and missing on some.
#
# Four of the five text faces are the DejaVu Sans family: regular, bold,
# oblique and bold oblique. A complete family is what lets a Bold or an
# Italic button work without the host loading anything, because asking for
# the bold member of a family only has an answer if the member is there.
# Two of them also fill a theme font slot; the two oblique faces fill none,
# and are here only to complete the family.
#
# String literals rather than a comma separated array of numbers: the bytes
# are identical and the compiler parses them about sixteen times faster, which
# matters when the faces come to some megabytes.
#
# Usage: sh scripts/embed_fonts.sh <output.c>
#
set -e

out="$1"
if [ -z "$out" ]; then
    echo "usage: sh scripts/embed_fonts.sh <output.c>" >&2
    exit 2
fi

here=$(dirname "$0")/..
fonts="$here/assets/fonts"

# Each line is one face: the file it comes from, the C name it takes, and the
# theme font slot it fills. SCHULTZ_TOKEN_FONT_COUNT means it fills none.
faces="DejaVuSans.ttf:schultz_face_body:SCHULTZ_TOKEN_FONT_BODY
DejaVuSans-Bold.ttf:schultz_face_title:SCHULTZ_TOKEN_FONT_TITLE
DejaVuSans-Oblique.ttf:schultz_face_oblique:SCHULTZ_TOKEN_FONT_COUNT
DejaVuSans-BoldOblique.ttf:schultz_face_bold_oblique:SCHULTZ_TOKEN_FONT_COUNT
DejaVuSansMono.ttf:schultz_face_mono:SCHULTZ_TOKEN_FONT_MONO
NotoColorEmoji-COLRv1.ttf:schultz_face_emoji:SCHULTZ_TOKEN_FONT_EMOJI"

emit_face() {
    _file="$1"
    _name="$2"

    if [ ! -f "$_file" ]; then
        echo "embed_fonts: missing $_file" >&2
        exit 1
    fi
    # -v keeps repeated lines, which a font full of zero padding has plenty
    # of, and -to1 prints one byte per field as three octal digits, which is
    # exactly what a C escape wants.
    od -An -v -to1 "$_file" | awk -v name="$_name" '
        BEGIN { printf "static const unsigned char %s[] =\n", name; n = 0 }
        {
            printf "\""
            for (i = 1; i <= NF; i++) { printf "\\%s", $i }
            printf "\"\n"
            n += NF
        }
        END {
            printf ";\n"
            printf "static const size_t %s_size = %dU;\n\n", name, n
        }'
}

{
    echo "/*"
    echo " * SPDX-License-Identifier: GPL-3.0-only AND OFL-1.1 AND Bitstream-Vera"
    echo " * Copyright 2026 Austin Lehman"
    echo " *"
    echo " * Generated by scripts/embed_fonts.sh. Do not edit."
    echo " *"
    echo " * The bundled faces, compiled in. The font data below is NOT under"
    echo " * this file's license: each face keeps its own, and both require"
    echo " * that their notice travels with any binary built from this file."
    echo " *"
    echo " * DejaVu (Sans regular, bold, oblique and bold oblique, and mono)"
    echo " *   Bitstream Vera Fonts License, plus public domain DejaVu"
    echo " *   changes. Full text in assets/fonts/LICENSE-DejaVu.txt."
    echo " *"
    echo " * Noto Color Emoji (emoji)"
    echo " *   Copyright 2022 Google Inc."
    echo " *   Licensed under the SIL Open Font License, Version 1.1."
    echo " *   Full text in assets/fonts/LICENSE-Noto.txt and at"
    echo " *   http://scripts.sil.org/OFL"
    echo " *   Noto is a trademark of Google Inc. The face is embedded"
    echo " *   unmodified; nothing here implies Google endorses this work."
    echo " *"
    echo " * See THIRD_PARTY_NOTICES.md."
    echo " */"
    echo
    echo "#include <stddef.h>"
    echo
    echo "#include \"schultz_font_builtin.h\""
    echo

    echo "$faces" | while IFS=: read -r file name token; do
        emit_face "$fonts/$file" "$name"
    done

    printf 'uint32_t schultz_font_builtin_count(void)\n{\n    return %dU;\n}\n\n' \
           "$(echo "$faces" | wc -l)"

    echo "const unsigned char *schultz_font_builtin_face(uint32_t index,"
    echo "                                               size_t *out_size,"
    echo "                                               uint32_t *out_token)"
    echo "{"
    echo "    switch (index) {"
    echo "$faces" | { i=0; while IFS=: read -r file name token; do
        echo "    case ${i}U:"
        echo "        *out_size  = ${name}_size;"
        echo "        *out_token = ${token};"
        echo "        return ${name};"
        i=$((i + 1))
    done; }
    echo "    default:"
    echo "        break;"
    echo "    }"
    echo "    *out_size  = 0U;"
    echo "    *out_token = SCHULTZ_TOKEN_FONT_COUNT;"
    echo "    return NULL;"
    echo "}"
} > "$out"
