# SPDX-License-Identifier: GPL-3.0-only
# Copyright 2026 Austin Lehman
#
# The pinned dependency set. Sourced by scripts/build_deps.sh, which builds
# them, and by scripts/fetch_sources.sh, which re-downloads them when a
# version here changes.
#
# Every archive named here is vendored in third_party/src, so a build needs no
# network. The URL and SHA-256 stay recorded because they are the audit trail:
# anyone can check the vendored file against what upstream published.

SDL_VERSION=3.4.16
SDL_SHA256=7322236cd12090c3eb40b9728be4d49c76f66ad17d04369584d4ecad5cf77c68
SDL_FILE="SDL3-${SDL_VERSION}.tar.gz"
SDL_URL="https://github.com/libsdl-org/SDL/releases/download/release-${SDL_VERSION}/${SDL_FILE}"

# SDL_mixer decodes what SDL itself does not: MP3, FLAC, Ogg Vorbis, Opus and
# WavPack on top of WAV. Its copyleft decoders are switched off where it is
# built; see scripts/build_deps.sh and THIRD_PARTY_NOTICES.md.
MIX_VERSION=3.2.4
MIX_SHA256=182a07c745375e113dc740d43964ff21b0be29f29f59876c4dbc4db3d32f6901
MIX_FILE="SDL3_mixer-${MIX_VERSION}.tar.gz"
MIX_URL="https://github.com/libsdl-org/SDL_mixer/releases/download/release-${MIX_VERSION}/${MIX_FILE}"

# The audio codecs, all built before SDL_mixer, which links them.
#
# Four of the five formats SDL_mixer can decode have two decoders: a small
# single file one bundled inside SDL_mixer, and the format author's own
# library. These are the authors' own, and SDL_mixer is built against them
# rather than against the bundled copies. They decode more of each format,
# they are the code every other player uses, and a security advisory against
# one of them is published rather than left for somebody to notice.
#
# Opus and WavPack have no bundled decoder at all, so they are formats the
# toolkit could not play before.
#
# Every one of these is BSD style. THIRD_PARTY_NOTICES.md records each.
#
# Build order: libogg first, since Vorbis, FLAC and Opus all store their
# packets in Ogg containers and every one of the three looks for it.
OGG_VERSION=1.3.6
OGG_SHA256=5c8253428e181840cd20d41f3ca16557a9cc04bad4a3d04cce84808677fa1061
OGG_FILE="libogg-${OGG_VERSION}.tar.xz"
OGG_URL="https://downloads.xiph.org/releases/ogg/${OGG_FILE}"

# libvorbis builds three libraries; SDL_mixer links vorbisfile, which is the
# one that reads a whole Ogg Vorbis file rather than raw Vorbis packets.
VORBIS_VERSION=1.3.7
VORBIS_SHA256=b33cc4934322bcbf6efcbacf49e3ca01aadbea4114ec9589d1b1e9d20f72954b
VORBIS_FILE="libvorbis-${VORBIS_VERSION}.tar.xz"
VORBIS_URL="https://downloads.xiph.org/releases/vorbis/${VORBIS_FILE}"

# This archive holds both libFLAC and the flac and metaflac command line
# tools, and the two are not under the same licence: the library is BSD and
# the tools are GPL. Only the library is built, which is what BUILD_PROGRAMS
# off means in scripts/build_deps.sh. See THIRD_PARTY_NOTICES.md.
FLAC_VERSION=1.5.0
FLAC_SHA256=f2c1c76592a82ffff8413ba3c4a1299b6c7ab06c734dee03fd88630485c2b920
FLAC_FILE="flac-${FLAC_VERSION}.tar.xz"
FLAC_URL="https://downloads.xiph.org/releases/flac/${FLAC_FILE}"

# Opus. Royalty free by design and the best of these at low bit rates, which
# is why voice chat and web calls all use it.
OPUS_VERSION=1.5.2
OPUS_SHA256=65c1d2f78b9f2fb20082c38cbe47c951ad5839345876e46941612ee87f9a7ce1
OPUS_FILE="opus-${OPUS_VERSION}.tar.gz"
OPUS_URL="https://downloads.xiph.org/releases/opus/${OPUS_FILE}"

# speexdsp: what a microphone needs before its samples are worth sending.
#
# Echo cancellation, noise suppression, automatic gain and voice detection.
# None of it is coding, and Opus does none of it: a call that sends the
# microphone straight to the encoder sends the far end its own voice back.
#
# A release tarball, not a source archive generated by the forge. The forge
# one is at gitlab.xiph.org/xiph/speexdsp/-/archive/... and was rejected for
# the reason libyuv was: an archive a server builds on demand is not a thing
# that can be pinned. This is the same downloads.xiph.org that Opus, FLAC and
# libogg already come from.
#
# Seven copyright holders, not one. See THIRD_PARTY_NOTICES.md.
SPEEXDSP_VERSION=1.2.1
SPEEXDSP_SHA256=8c777343e4a6399569c72abc38a95b24db56882c83dbdb6c6424a5f4aeb54d3d
SPEEXDSP_FILE="speexdsp-${SPEEXDSP_VERSION}.tar.gz"
SPEEXDSP_URL="https://downloads.xiph.org/releases/speex/${SPEEXDSP_FILE}"

# opusfile reads an .opus file; libopus alone only decodes packets.
#
# The odd one out, and the only dependency here that is not a release. Xiph
# has published no opusfile release since 0.12 in 2020, and 0.12 builds with
# autotools only, which nothing else here uses and which cannot follow the
# CMake toolchain files the cross targets are built with. CMake support
# landed upstream after 0.12, so this is a commit from Xiph's own repository
# rather than a fork: the tree that "git describe" calls v0.12-59-g6dfd29e.
# SDL_mixer makes the same choice, vendoring a post-0.12 snapshot of its own.
#
# A GitHub commit archive is not promised to be byte for byte stable, so this
# checksum may one day stop matching a fresh download even though the commit
# has not changed. That breaks nothing: the archive is in git and no build
# reaches the network. It would mean re-checking the contents by hand before
# recording a new hash.
#
# THIRD_PARTY_NOTICES.md, "opusfile is pinned to a commit, not a release", has
# the rest: what was checked before accepting it, and what to do if Xiph ever
# publishes a release that ships a CMakeLists.txt.
OPUSFILE_VERSION=0.12-59-g6dfd29e
OPUSFILE_COMMIT=6dfd29e7adb87f2e193575fc3fa88cbf1a0b27df
OPUSFILE_SHA256=7dcaea4385d9020dc3c02a8d01bce6ba17576bbda4b126434a90d74ba6bec29d
OPUSFILE_FILE="opusfile-${OPUSFILE_VERSION}.tar.gz"
OPUSFILE_URL="https://github.com/xiph/opusfile/archive/${OPUSFILE_COMMIT}.tar.gz"

# WavPack. Lossless like FLAC, and also a hybrid mode nothing else here has:
# a small lossy file beside a correction file that restores the original.
WAVPACK_VERSION=5.9.0
WAVPACK_SHA256=b5291bc4e6d69ebbd3da3800c5bf4a70f19bb92679b23e09b3b612c1e648d1ff
WAVPACK_FILE="wavpack-${WAVPACK_VERSION}.tar.xz"
WAVPACK_URL="https://github.com/dbry/WavPack/releases/download/${WAVPACK_VERSION}/${WAVPACK_FILE}"

TVG_VERSION=1.1.1
TVG_SHA256=5ca6143088f18b5dbe42552c939594100da6226d79de503d1a171184d6aa310d
TVG_FILE="thorvg-${TVG_VERSION}.tar.xz"
TVG_URL="https://github.com/thorvg/thorvg/releases/download/v${TVG_VERSION}/${TVG_FILE}"

# The image codecs. ThorVG decodes PNG and WebP through these, and FreeType
# reads PNG for colour bitmap fonts. They are vendored for the same reason
# everything else is: there is no system copy of any of them on a phone, and
# without them a build for one silently loses PNG and WebP support.
#
# Build order: zlib, then libpng which needs it, then libwebp. All three come
# before FreeType and ThorVG, which look for them.
ZLIB_VERSION=1.3.2
ZLIB_SHA256=bb329a0a2cd0274d05519d61c667c062e06990d72e125ee2dfa8de64f0119d16
ZLIB_FILE="zlib-${ZLIB_VERSION}.tar.gz"
ZLIB_URL="https://zlib.net/${ZLIB_FILE}"

PNG_VERSION=1.6.58
PNG_SHA256=28eb403f51f0f7405249132cecfe82ea5c0ef97f1b32c5a65828814ae0d34775
PNG_FILE="libpng-${PNG_VERSION}.tar.xz"
PNG_URL="https://downloads.sourceforge.net/project/libpng/libpng16/${PNG_VERSION}/${PNG_FILE}"

# sharpyuv is built from this same tree; it is not a separate download.
WEBP_VERSION=1.6.0
WEBP_SHA256=e4ab7009bf0629fd11982d4c2aa83964cf244cffba7347ecd39019a9e38c4564
WEBP_FILE="libwebp-${WEBP_VERSION}.tar.gz"
WEBP_URL="https://storage.googleapis.com/downloads.webmproject.org/releases/webp/${WEBP_FILE}"

# The JPEG decoder ThorVG uses, and the reason it is pinned here rather than
# left to the machine.
#
# ThorVG's JPEG loader asks for libturbojpeg and falls back to a decoder it
# carries when there is none. That made which decoder shipped a property of
# the build machine: a Mac with Homebrew's copy built against it, a Linux box
# without one did not, and the first kind produced a library needing something
# that was never vendored. Pinning it here answers the question the same way
# everywhere.
#
# Two BSD style licences, both permissive: the IJG licence for the libjpeg API
# and 3-clause BSD for the TurboJPEG API on top of it. See
# THIRD_PARTY_NOTICES.md.
JPEG_VERSION=3.2.0
JPEG_SHA256=6f30092cef9fb839779646608f4ee14ae3cbac989c47fa05e841b0841f09878e
JPEG_FILE="libjpeg-turbo-${JPEG_VERSION}.tar.gz"
JPEG_URL="https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/${JPEG_VERSION}/${JPEG_FILE}"

# Build order matters: HarfBuzz is built against FreeType, so FreeType comes
# first with its own HarfBuzz support switched off.
FT_VERSION=2.14.3
FT_SHA256=36bc4f1cc413335368ee656c42afca65c5a3987e8768cc28cf11ba775e785a5f
FT_FILE="freetype-${FT_VERSION}.tar.xz"
FT_URL="https://download.savannah.gnu.org/releases/freetype/${FT_FILE}"

HB_VERSION=14.4.0
HB_SHA256=2357ed966c6ced7bfa720b0640c0231065af01158fbea215093ffa15aed44371
HB_FILE="harfbuzz-${HB_VERSION}.tar.xz"
HB_URL="https://github.com/harfbuzz/harfbuzz/releases/download/${HB_VERSION}/${HB_FILE}"

SB_VERSION=3.0.0
SB_SHA256=86c56014034739ba39a24c23eb00323b0bf6f737354f665786015fca842af786
SB_FILE="SheenBidi-${SB_VERSION}.tar.gz"
SB_URL="https://github.com/Tehreer/SheenBidi/archive/refs/tags/v${SB_VERSION}.tar.gz"

UB_VERSION=7.0
UB_SHA256=8c9a6e121736cd0d5c890ae3ae96f3f4010a19aa040f1dbded833a62a87717d3
UB_FILE="libunibreak-${UB_VERSION}.tar.gz"
UB_URL="https://github.com/adah1972/libunibreak/releases/download/libunibreak_7_0/${UB_FILE}"

# The bundled default font. Rendering is then identical on every target,
# because the font ships with the toolkit rather than being discovered.
FONT_VERSION=2.37
FONT_SHA256=fa9ca4d13871dd122f61258a80d01751d603b4d3ee14095d65453b4e846e17d7
FONT_FILE="dejavu-fonts-ttf-${FONT_VERSION}.tar.bz2"
FONT_URL="https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_${FONT_VERSION%.*}_${FONT_VERSION#*.}/${FONT_FILE}"

# libvpx decodes VP8 and VP9, which are the two video codecs this project can
# ship: both are royalty free under an irrevocable grant from Google, and
# VP8's is stronger still because the patent pool that formed against it was
# bought out and dissolved in 2013. Every other codec was rejected on the
# same ground: a licence that cannot be shipped without paying for it.
#
# Decoders only. The encoders are switched off in scripts/build_deps.sh until
# the outbound half is built, because half a megabyte of encoder that nothing
# calls is half a megabyte.
#
# libvpx ships a PATENTS file separate from LICENSE. It is the grant the codec
# choice rests on and is reproduced in full in THIRD_PARTY_NOTICES.md.
LIBVPX_VERSION=1.15.0
LIBVPX_SHA256=e935eded7d81631a538bfae703fd1e293aad1c7fd3407ba00440c95105d2011e
LIBVPX_FILE="libvpx-${LIBVPX_VERSION}.tar.gz"
LIBVPX_URL="https://github.com/webmproject/libvpx/archive/refs/tags/v${LIBVPX_VERSION}.tar.gz"

# nestegg reads WebM, which is the container VP8, VP9 and Opus travel in. One
# C file and one header, so it is compiled into the toolkit from
# third_party/nestegg rather than built as a library, the same way libunibreak
# is.
#
# Pinned to a commit rather than a release, because it has never made one.
# opusfile is the other dependency in this position; both are explained in
# THIRD_PARTY_NOTICES.md.
NESTEGG_COMMIT=d6ec55624d8187a2699ac890b83460b973331400
NESTEGG_SHA256=f8bbd44412953f0f99e88b4f8913ce42fdbadd1321bf4882e4d13e6774a3cf5a
NESTEGG_FILE="nestegg-${NESTEGG_COMMIT}.tar.gz"
NESTEGG_URL="https://github.com/mozilla/nestegg/archive/${NESTEGG_COMMIT}.tar.gz"

# The bundled emoji face. One font in one format on every target, for the
# same reason as the one above: an emoji discovered from the system is a
# different picture on every platform, and missing entirely on some.
#
# COLR version 1, which describes each emoji as a small drawing: shapes
# filled with colours and gradients, moved, clipped and layered. FreeType
# reads it and does not draw it, so schultz_colr.c walks the description and
# draws it with the vector engine the toolkit already carries.
#
# Version 1 rather than the older version 0, which stores flat layers and
# which FreeType draws by itself. Nobody has published a version 0 emoji font
# since 2022, so every one of them is missing the last two Unicode releases;
# this one is maintained and covers all 3781 emoji Unicode defines.
#
# Not an archive: the repository publishes the .ttf itself, so the checksum
# is of the font file rather than of a tarball holding it.
EMOJI_VERSION=2.051
EMOJI_SHA256=0ae57fe58645638523ba35f388d93739d292539a9acb84df5700c81b1e1a28d2
EMOJI_FILE="Noto-COLRv1.ttf"
EMOJI_URL="https://github.com/googlefonts/noto-emoji/raw/main/fonts/${EMOJI_FILE}"

ALL_ARCHIVES="$SDL_FILE $MIX_FILE $TVG_FILE $FT_FILE $HB_FILE $SB_FILE
$UB_FILE $FONT_FILE $ZLIB_FILE $PNG_FILE $WEBP_FILE $OGG_FILE $VORBIS_FILE
$FLAC_FILE $OPUS_FILE $OPUSFILE_FILE $WAVPACK_FILE $JPEG_FILE $LIBVPX_FILE
$NESTEGG_FILE $SPEEXDSP_FILE"
